name: Benchmarking
on:
  issue_comment:
    types: [created]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, plutus-benchmark]
    
    if: | 
      startsWith(github.event.comment.body, '/benchmark') && 
      github.event.issue.pull_request 

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: React with Rocket 
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue;
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });  

      #
      # Extract the branch of that the PR the comment was added to belongs to
      #
      - uses: xt0rted/pull-request-comment-branch@v1
        if: success()
        id: extract-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      #
      # Extract the benchmark name from the comment text
      #
      - uses: actions-ecosystem/action-regex-match@v2
        if: success()
        id: extract-benchmark
        with:
          # The 'pull-request-comment-trigger` action alleges that you 
          # can get the matched comment via its comment_body output, but
          # this is a lie: https://github.com/Khan/pull-request-comment-trigger/issues/6
          text: ${{ github.event.comment.body }}
          regex: '^\/benchmark\s*(.*?)\s*$'

      #
      # Run the benchmark if the 'benchmark' command was found
      #
      - run: |
         nix develop --no-warn-dirty --accept-flake-config --command bash ./scripts/ci-plutus-benchmark.sh ${{ github.event.issue.number }} ${{ steps.extract-benchmark.outputs.group1 }}
        if: success()
